# Generated by Django 3.2.2 on 2021-08-31 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('dj_id', models.AutoField(primary_key=True, serialize=False)),
                ('dj_name', models.CharField(max_length=100)),
                ('dj_email', models.EmailField(max_length=100)),
                ('dj_website', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('dj_image', models.FileField(blank=True, upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'DJS',
            },
        ),
        migrations.CreateModel(
            name='DjMixTape',
            fields=[
                ('mix_tape_id', models.AutoField(primary_key=True, serialize=False)),
                ('mix_tape_title', models.CharField(max_length=200)),
                ('mix_tape_media_link', models.FileField(blank=True, upload_to='videos')),
                ('mix_tape_tot_likes', models.IntegerField(blank=True, default=None, null=True)),
                ('mix_tape_tot_views', models.IntegerField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('dj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixtapes.dj')),
            ],
            options={
                'verbose_name_plural': 'DJ Mix Tapes',
                'ordering': ['created_on'],
            },
        ),
    ]
