# Generated by Django 3.2.2 on 2021-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixtapes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmixtape',
            name='mix_tape_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
