# Generated by Django 3.2.2 on 2021-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixtapes', '0002_alter_djmixtape_mix_tape_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmixtape',
            name='mix_tape_tot_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='djmixtape',
            name='mix_tape_tot_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
