# Generated by Django 3.2.2 on 2021-08-31 14:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixtapes', '0003_auto_20210831_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmixtape',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='mix_tape_title'),
        ),
    ]
