# Generated by Django 3.2.2 on 2021-08-31 14:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixtapes', '0004_alter_djmixtape_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmixtape',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='created_on,mix_tape_title'),
        ),
    ]
