# Generated by Django 3.2.2 on 2021-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('dj_id', models.AutoField(primary_key=True, serialize=False)),
                ('dj_name', models.CharField(max_length=100)),
                ('dj_email', models.EmailField(max_length=100)),
                ('dj_website', models.URLField(max_length=100)),
            ],
        ),
    ]
