# Generated by Django 3.2.2 on 2021-05-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0004_alter_dj_dj_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjMixTape',
            fields=[
                ('mix_tape_id', models.AutoField(primary_key=True, serialize=False)),
                ('mix_tape_title', models.CharField(max_length=200)),
                ('mix_tape_media_link', models.FileField(blank=True, upload_to='videos')),
                ('mix_tape_tot_likes', models.IntegerField(blank=True, default=0)),
                ('mix_tape_tot_views', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('dj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnpulseapp.dj')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
