# Generated by Django 3.2.2 on 2021-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0005_djmixtape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmixtape',
            name='mix_tape_tot_likes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='djmixtape',
            name='mix_tape_tot_views',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
