# Generated by Django 3.2.2 on 2021-05-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0006_auto_20210511_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmixtape',
            name='dj_id',
            field=models.ForeignKey(db_column='dj_name', on_delete=django.db.models.deletion.CASCADE, to='mtnpulseapp.dj'),
        ),
    ]
