# Generated by Django 3.2.2 on 2021-05-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0007_alter_djmixtape_dj_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='mix_image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
