# Generated by Django 3.2.2 on 2021-05-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0009_rename_mix_image_dj_dj_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='dj_image',
        ),
    ]
