# Generated by Django 3.2.2 on 2021-05-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0010_remove_dj_dj_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='dj_image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
