# Generated by Django 3.2.2 on 2021-05-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0011_dj_dj_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmixtape',
            name='dj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnpulseapp.dj'),
        ),
    ]
