# Generated by Django 3.2.2 on 2021-05-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0012_alter_djmixtape_dj_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLink',
            fields=[
                ('live_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('live_link_title', models.CharField(max_length=100)),
                ('live_link_url', models.URLField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
