# Generated by Django 3.2.2 on 2021-05-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0013_livelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livelink',
            options={'ordering': ['created_on']},
        ),
    ]
