# Generated by Django 3.2.2 on 2021-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0014_alter_livelink_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('archive_id', models.AutoField(primary_key=True, serialize=False)),
                ('archive_title', models.CharField(max_length=100)),
                ('archive_url', models.FileField(upload_to='archives')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
