# Generated by Django 3.2.2 on 2021-08-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0015_archives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djmixtape',
            name='dj_id',
        ),
        migrations.AlterModelOptions(
            name='archives',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Archives'},
        ),
        migrations.AlterModelOptions(
            name='livelink',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Live Links'},
        ),
        migrations.DeleteModel(
            name='Dj',
        ),
        migrations.DeleteModel(
            name='DjMixTape',
        ),
    ]
