# Generated by Django 3.2.2 on 2021-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0016_auto_20210831_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBeats',
            fields=[
                ('news_beat_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_beat_title', models.CharField(max_length=100, unique=True)),
                ('news_beat_url', models.FileField(blank=True, upload_to='videos')),
                ('news_beat_tot_likes', models.IntegerField(blank=True, default=None, null=True)),
                ('news_beat_tot_views', models.IntegerField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News Beat',
                'ordering': ['created_on'],
            },
        ),
        migrations.AlterField(
            model_name='archives',
            name='archive_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
