# Generated by Django 3.2.2 on 2021-08-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0017_auto_20210831_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsbeats',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'News Beats'},
        ),
        migrations.AlterField(
            model_name='newsbeats',
            name='news_beat_tot_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='newsbeats',
            name='news_beat_tot_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
