# Generated by Django 3.2.2 on 2021-08-31 14:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0018_auto_20210831_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbeats',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='created_on,news_beat_title', unique=True),
        ),
    ]
