# Generated by Django 3.2.2 on 2021-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnpulseapp', '0019_alter_newsbeats_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='archive_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archives',
            name='archive_presenter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archives',
            name='archive_tot_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='archives',
            name='archive_tot_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='livelink',
            name='live_link_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livelink',
            name='live_link_show_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livelink',
            name='live_link_tot_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='livelink',
            name='live_link_tot_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
